# Generated by Django 5.0.6 on 2024-07-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(default='arrendatario', max_length=255),
        ),
    ]
