# Generated by Django 5.0.6 on 2024-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_rol_alter_userprofile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='imagen1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='imagen3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
